### ISSUE TITLE
automated backup

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/DRR#58]
I've gotten this:

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/chris/code/ghub/DRR/server/lib/file.py", line 118, in prune_process

  File "/home/chris/code/ghub/DRR/server/lib/file.py", line 75, in register_streams
    all_registered = Set(DB.all('streams', ['name']))
  File "/home/chris/code/ghub/DRR/server/lib/db.py", line 70, in all
    return [record[0] for record in query.fetchall()]
DatabaseError: database disk image is malformed

As long as I do rolling backups I shouldn't get issues ... a db endpoint is ideal.

**Comment by kristopolous** [comment]
created a backup system ... i guess restore will be on me
